export enum ErrorCode {
  ACCOUNT_IS_NOT_FOUND = 'ACCOUNT_IS_NOT_FOUND',
  CAN_NOT_SET_PASSWORD = 'CAN_NOT_SET_PASSWORD',
  CAN_NOT_WITHDRAW_UNDER_1 = 'CAN_NOT_WITHDRAW_UNDER_1',
  REQUESTED_AMOUNT_EXCEEDS_YOUR_WITHDRAWAL_LIMIT = 'REQUESTED_AMOUNT_EXCEEDS_YOUR_WITHDRAWAL_LIMIT',
  CAN_NOT_DEPOSIT_UNDER_1 = 'CAN_NOT_DEPOSIT_UNDER_1',
  ACCOUNT_BALANCE_IS_REMAINED = 'ACCOUNT_BALANCE_IS_REMAINED',
  WITHDRAWAL_AND_DEPOSIT_ACCOUNTS_CANNOT_BE_THE_SAME = 'WITHDRAWAL_AND_DEPOSIT_ACCOUNTS_CANNOT_BE_THE_SAME',
  ACCOUNT_IS_ALREADY_LOCKED = 'ACCOUNT_IS_ALREADY_LOCKED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
